controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 10.0

    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"

      # Safe speeds (elderly-care)
      max_vel_x: 0.25
      min_vel_x: 0.0
      max_vel_theta: 1.0
      min_vel_theta: -1.0

      acc_lim_x: 0.8
      acc_lim_theta: 1.2

      vx_samples: 20
      vtheta_samples: 40
      sim_time: 1.5

      critics:
        - BaseObstacle
        - PathAlign
        - GoalAlign
        - PathDist
        - GoalDist

      BaseObstacle.scale: 0.02
      PathAlign.scale: 32.0
      GoalAlign.scale: 24.0
      PathDist.scale: 32.0
      GoalDist.scale: 24.0

